// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public static event Action<ClientApi.Event.Types.Status, Identity, string> OnCreatePlayerEvent;

		public static void CreatePlayer(string username)
		{
			var _argArray = new object[] {username};
			var _message = new NetworkManager.ReducerCallRequest {
				fn = "create_player",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			NetworkManager.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerEvent(FunctionName = "create_player")]
		public static void OnCreatePlayer(ClientApi.Event dbEvent)
		{
			if(OnCreatePlayerEvent != null)
			{
				var args = dbEvent.FunctionCall.CallInfo.CreatePlayerArgs;
				OnCreatePlayerEvent(dbEvent.Status, Identity.From(dbEvent.CallerIdentity.ToByteArray())
					,(string)args.Username
				);
			}
		}
		[DeserializeEvent(FunctionName = "create_player")]
		public static void CreatePlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new CreatePlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Username = args_0_value.AsString();
			var argsGeneric = new ReducerArgs();
			argsGeneric.CreatePlayerArgs = args;
			dbEvent.FunctionCall.CallInfo = new ReducerCallInfo(ReducerType.CreatePlayer, dbEvent.Message, dbEvent.Status, argsGeneric);
		}
	}

	public struct CreatePlayerArgsStruct
	{
		public string Username;
	}

	public partial struct ReducerArgs
	{
		[System.Runtime.InteropServices.FieldOffset(0)]
		public CreatePlayerArgsStruct CreatePlayerArgs;
	}

	public partial class ReducerCallInfo
	{
		public CreatePlayerArgsStruct CreatePlayerArgs
		{
			get
			{
				if (Reducer != ReducerType.CreatePlayer) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "CreatePlayer");
				return Args.CreatePlayerArgs;
			}
		}
	}
}
