// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public static event Action<ClientApi.Event.Types.Status, Identity, SpacetimeDB.StdbVector2, SpacetimeDB.StdbVector2> OnMovePlayerEvent;

		public static void MovePlayer(SpacetimeDB.StdbVector2 start, SpacetimeDB.StdbVector2 direction)
		{
			var _argArray = new object[] {start, direction};
			var _message = new NetworkManager.ReducerCallRequest {
				fn = "move_player",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			NetworkManager.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerEvent(FunctionName = "move_player")]
		public static void OnMovePlayer(ClientApi.Event dbEvent)
		{
			if(OnMovePlayerEvent != null)
			{
				var args = dbEvent.FunctionCall.CallInfo.MovePlayerArgs;
				OnMovePlayerEvent(dbEvent.Status, Identity.From(dbEvent.CallerIdentity.ToByteArray())
					,(SpacetimeDB.StdbVector2)args.Start
					,(SpacetimeDB.StdbVector2)args.Direction
				);
			}
		}
		[DeserializeEvent(FunctionName = "move_player")]
		public static void MovePlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new MovePlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector2.GetAlgebraicType(), reader);
			args.Start = (SpacetimeDB.StdbVector2)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector2.GetAlgebraicType(), reader);
			args.Direction = (SpacetimeDB.StdbVector2)(args_1_value);
			var argsGeneric = new ReducerArgs();
			argsGeneric.MovePlayerArgs = args;
			dbEvent.FunctionCall.CallInfo = new ReducerCallInfo(ReducerType.MovePlayer, dbEvent.Message, dbEvent.Status, argsGeneric);
		}
	}

	public struct MovePlayerArgsStruct
	{
		public SpacetimeDB.StdbVector2 Start;
		public SpacetimeDB.StdbVector2 Direction;
	}

	public partial struct ReducerArgs
	{
		[System.Runtime.InteropServices.FieldOffset(0)]
		public MovePlayerArgsStruct MovePlayerArgs;
	}

	public partial class ReducerCallInfo
	{
		public MovePlayerArgsStruct MovePlayerArgs
		{
			get
			{
				if (Reducer != ReducerType.MovePlayer) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "MovePlayer");
				return Args.MovePlayerArgs;
			}
		}
	}
}
