// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public enum ReducerType
	{
		CreatePlayer,
		MovePlayer,
		ResourceSpawnerAgent,
		StopPlayer,
	}

	public partial class ReducerCallInfo
	{
		public ReducerType Reducer { get; private set; }
		public string ErrMessage { get; private set; }
		public ClientApi.Event.Types.Status Status { get; private set; }
		private ReducerArgs Args;

		public ReducerCallInfo(ReducerType reducer, string errMessage, ClientApi.Event.Types.Status status, ReducerArgs args)
		{
			Reducer = reducer;
			ErrMessage = errMessage;
			Status = status;
			Args = args;
		}

		public object[] GetArgsAsObjectArray()
		{
			switch (Reducer)
			{
				case ReducerType.CreatePlayer:
				{
					var args = CreatePlayerArgs;
					return new object[] {
						args.Username,
					};
				}
				case ReducerType.MovePlayer:
				{
					var args = MovePlayerArgs;
					return new object[] {
						args.Start,
						args.Direction,
					};
				}
				case ReducerType.ResourceSpawnerAgent:
				{
					var args = ResourceSpawnerAgentArgs;
					return new object[] {
						args.PrevTime,
					};
				}
				case ReducerType.StopPlayer:
				{
					var args = StopPlayerArgs;
					return new object[] {
						args.Location,
					};
				}
				default: throw new System.Exception($"Unhandled reducer case: {Reducer}. Please run SpacetimeDB code generator");
			}
		}
	}
	[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]
	public partial struct ReducerArgs { }
}
