// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public static event Action<ClientApi.Event.Types.Status, Identity, ulong> OnResourceSpawnerAgentEvent;

		public static void ResourceSpawnerAgent(ulong prevTime)
		{
			var _argArray = new object[] {prevTime};
			var _message = new NetworkManager.ReducerCallRequest {
				fn = "resource_spawner_agent",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			NetworkManager.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerEvent(FunctionName = "resource_spawner_agent")]
		public static void OnResourceSpawnerAgent(ClientApi.Event dbEvent)
		{
			if(OnResourceSpawnerAgentEvent != null)
			{
				var args = dbEvent.FunctionCall.CallInfo.ResourceSpawnerAgentArgs;
				OnResourceSpawnerAgentEvent(dbEvent.Status, Identity.From(dbEvent.CallerIdentity.ToByteArray())
					,(ulong)args.PrevTime
				);
			}
		}
		[DeserializeEvent(FunctionName = "resource_spawner_agent")]
		public static void ResourceSpawnerAgentDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new ResourceSpawnerAgentArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.PrevTime = args_0_value.AsU64();
			var argsGeneric = new ReducerArgs();
			argsGeneric.ResourceSpawnerAgentArgs = args;
			dbEvent.FunctionCall.CallInfo = new ReducerCallInfo(ReducerType.ResourceSpawnerAgent, dbEvent.Message, dbEvent.Status, argsGeneric);
		}
	}

	public struct ResourceSpawnerAgentArgsStruct
	{
		public ulong PrevTime;
	}

	public partial struct ReducerArgs
	{
		[System.Runtime.InteropServices.FieldOffset(0)]
		public ResourceSpawnerAgentArgsStruct ResourceSpawnerAgentArgs;
	}

	public partial class ReducerCallInfo
	{
		public ResourceSpawnerAgentArgsStruct ResourceSpawnerAgentArgs
		{
			get
			{
				if (Reducer != ReducerType.ResourceSpawnerAgent) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "ResourceSpawnerAgent");
				return Args.ResourceSpawnerAgentArgs;
			}
		}
	}
}
