// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class ResourceNodeComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;
		[Newtonsoft.Json.JsonProperty("resource_type")]
		public string ResourceType;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("resource_type", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String)),
			});
		}

		public static explicit operator ResourceNodeComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new ResourceNodeComponent
			{
				EntityId = productValue.elements[0].AsU64(),
				ResourceType = productValue.elements[1].AsString(),
			};
		}

		public static System.Collections.Generic.IEnumerable<ResourceNodeComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ResourceNodeComponent"))
			{
				yield return (ResourceNodeComponent)entry.Item2;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("ResourceNodeComponent");
		}
		public static ResourceNodeComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ResourceNodeComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (ResourceNodeComponent)entry.Item2;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<ResourceNodeComponent> FilterByResourceType(string value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ResourceNodeComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (string)productValue.elements[1].AsString();
				if (compareValue == value) {
					yield return (ResourceNodeComponent)entry.Item2;
				}
			}
		}

		public static bool ComparePrimaryKey(SpacetimeDB.SATS.AlgebraicType t, SpacetimeDB.SATS.AlgebraicValue _v1, SpacetimeDB.SATS.AlgebraicValue _v2)
		{
			return false;
		}

		public delegate void InsertEventHandler(ResourceNodeComponent insertedValue, ClientApi.Event dbEvent);
		public delegate void UpdateEventHandler(ResourceNodeComponent oldValue, ResourceNodeComponent newValue, ClientApi.Event dbEvent);
		public delegate void DeleteEventHandler(ResourceNodeComponent deletedValue, ClientApi.Event dbEvent);
		public delegate void RowUpdateEventHandler(NetworkManager.TableOp op, ResourceNodeComponent oldValue, ResourceNodeComponent newValue, ClientApi.Event dbEvent);
		public static event InsertEventHandler OnInsert;
		public static event UpdateEventHandler OnUpdate;
		public static event DeleteEventHandler OnDelete;
		public static event RowUpdateEventHandler OnRowUpdate;

		public static void OnInsertEvent(object newValue, ClientApi.Event dbEvent)
		{
			OnInsert?.Invoke((ResourceNodeComponent)newValue,dbEvent);
		}

		public static void OnUpdateEvent(object oldValue, object newValue, ClientApi.Event dbEvent)
		{
			OnUpdate?.Invoke((ResourceNodeComponent)oldValue,(ResourceNodeComponent)newValue,dbEvent);
		}

		public static void OnDeleteEvent(object oldValue, ClientApi.Event dbEvent)
		{
			OnDelete?.Invoke((ResourceNodeComponent)oldValue,dbEvent);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue, ClientApi.Event dbEvent)
		{
			OnRowUpdate?.Invoke(op, (ResourceNodeComponent)oldValue,(ResourceNodeComponent)newValue,dbEvent);
		}
	}
}
