// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class SpawnableEntityComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
			});
		}

		public static explicit operator SpawnableEntityComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new SpawnableEntityComponent
			{
				EntityId = productValue.elements[0].AsU64(),
			};
		}

		public static System.Collections.Generic.IEnumerable<SpawnableEntityComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("SpawnableEntityComponent"))
			{
				yield return (SpawnableEntityComponent)entry.Item2;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("SpawnableEntityComponent");
		}
		public static SpawnableEntityComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("SpawnableEntityComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (SpawnableEntityComponent)entry.Item2;
				}
			}
			return null;
		}

		public static bool ComparePrimaryKey(SpacetimeDB.SATS.AlgebraicType t, SpacetimeDB.SATS.AlgebraicValue v1, SpacetimeDB.SATS.AlgebraicValue v2)
		{
			var primaryColumnValue1 = v1.AsProductValue().elements[0];
			var primaryColumnValue2 = v2.AsProductValue().elements[0];
			return SpacetimeDB.SATS.AlgebraicValue.Compare(t.product.elements[0].algebraicType, primaryColumnValue1, primaryColumnValue2);
		}

		public delegate void InsertEventHandler(SpawnableEntityComponent insertedValue, ClientApi.Event dbEvent);
		public delegate void UpdateEventHandler(SpawnableEntityComponent oldValue, SpawnableEntityComponent newValue, ClientApi.Event dbEvent);
		public delegate void DeleteEventHandler(SpawnableEntityComponent deletedValue, ClientApi.Event dbEvent);
		public delegate void RowUpdateEventHandler(NetworkManager.TableOp op, SpawnableEntityComponent oldValue, SpawnableEntityComponent newValue, ClientApi.Event dbEvent);
		public static event InsertEventHandler OnInsert;
		public static event UpdateEventHandler OnUpdate;
		public static event DeleteEventHandler OnDelete;
		public static event RowUpdateEventHandler OnRowUpdate;

		public static void OnInsertEvent(object newValue, ClientApi.Event dbEvent)
		{
			OnInsert?.Invoke((SpawnableEntityComponent)newValue,dbEvent);
		}

		public static void OnUpdateEvent(object oldValue, object newValue, ClientApi.Event dbEvent)
		{
			OnUpdate?.Invoke((SpawnableEntityComponent)oldValue,(SpawnableEntityComponent)newValue,dbEvent);
		}

		public static void OnDeleteEvent(object oldValue, ClientApi.Event dbEvent)
		{
			OnDelete?.Invoke((SpawnableEntityComponent)oldValue,dbEvent);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue, ClientApi.Event dbEvent)
		{
			OnRowUpdate?.Invoke(op, (SpawnableEntityComponent)oldValue,(SpawnableEntityComponent)newValue,dbEvent);
		}
	}
}
