// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class StaticLocationComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;
		[Newtonsoft.Json.JsonProperty("location")]
		public SpacetimeDB.StdbVector2 Location;
		[Newtonsoft.Json.JsonProperty("rotation")]
		public float Rotation;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("location", SpacetimeDB.StdbVector2.GetAlgebraicType()),
				new SpacetimeDB.SATS.ProductTypeElement("rotation", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.F32)),
			});
		}

		public static explicit operator StaticLocationComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new StaticLocationComponent
			{
				EntityId = productValue.elements[0].AsU64(),
				Location = (SpacetimeDB.StdbVector2)(productValue.elements[1]),
				Rotation = productValue.elements[2].AsF32(),
			};
		}

		public static System.Collections.Generic.IEnumerable<StaticLocationComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("StaticLocationComponent"))
			{
				yield return (StaticLocationComponent)entry.Item2;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("StaticLocationComponent");
		}
		public static StaticLocationComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("StaticLocationComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (StaticLocationComponent)entry.Item2;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<StaticLocationComponent> FilterByRotation(float value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("StaticLocationComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (float)productValue.elements[2].AsF32();
				if (compareValue == value) {
					yield return (StaticLocationComponent)entry.Item2;
				}
			}
		}

		public static bool ComparePrimaryKey(SpacetimeDB.SATS.AlgebraicType t, SpacetimeDB.SATS.AlgebraicValue v1, SpacetimeDB.SATS.AlgebraicValue v2)
		{
			var primaryColumnValue1 = v1.AsProductValue().elements[0];
			var primaryColumnValue2 = v2.AsProductValue().elements[0];
			return SpacetimeDB.SATS.AlgebraicValue.Compare(t.product.elements[0].algebraicType, primaryColumnValue1, primaryColumnValue2);
		}

		public delegate void InsertEventHandler(StaticLocationComponent insertedValue, ClientApi.Event dbEvent);
		public delegate void UpdateEventHandler(StaticLocationComponent oldValue, StaticLocationComponent newValue, ClientApi.Event dbEvent);
		public delegate void DeleteEventHandler(StaticLocationComponent deletedValue, ClientApi.Event dbEvent);
		public delegate void RowUpdateEventHandler(NetworkManager.TableOp op, StaticLocationComponent oldValue, StaticLocationComponent newValue, ClientApi.Event dbEvent);
		public static event InsertEventHandler OnInsert;
		public static event UpdateEventHandler OnUpdate;
		public static event DeleteEventHandler OnDelete;
		public static event RowUpdateEventHandler OnRowUpdate;

		public static void OnInsertEvent(object newValue, ClientApi.Event dbEvent)
		{
			OnInsert?.Invoke((StaticLocationComponent)newValue,dbEvent);
		}

		public static void OnUpdateEvent(object oldValue, object newValue, ClientApi.Event dbEvent)
		{
			OnUpdate?.Invoke((StaticLocationComponent)oldValue,(StaticLocationComponent)newValue,dbEvent);
		}

		public static void OnDeleteEvent(object oldValue, ClientApi.Event dbEvent)
		{
			OnDelete?.Invoke((StaticLocationComponent)oldValue,dbEvent);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue, ClientApi.Event dbEvent)
		{
			OnRowUpdate?.Invoke(op, (StaticLocationComponent)oldValue,(StaticLocationComponent)newValue,dbEvent);
		}
	}
}
