// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public static event Action<ClientApi.Event.Types.Status, Identity, SpacetimeDB.StdbVector2> OnStopPlayerEvent;

		public static void StopPlayer(SpacetimeDB.StdbVector2 location)
		{
			var _argArray = new object[] {location};
			var _message = new NetworkManager.ReducerCallRequest {
				fn = "stop_player",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			NetworkManager.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerEvent(FunctionName = "stop_player")]
		public static void OnStopPlayer(ClientApi.Event dbEvent)
		{
			if(OnStopPlayerEvent != null)
			{
				var args = dbEvent.FunctionCall.CallInfo.StopPlayerArgs;
				OnStopPlayerEvent(dbEvent.Status, Identity.From(dbEvent.CallerIdentity.ToByteArray())
					,(SpacetimeDB.StdbVector2)args.Location
				);
			}
		}
		[DeserializeEvent(FunctionName = "stop_player")]
		public static void StopPlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new StopPlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector2.GetAlgebraicType(), reader);
			args.Location = (SpacetimeDB.StdbVector2)(args_0_value);
			var argsGeneric = new ReducerArgs();
			argsGeneric.StopPlayerArgs = args;
			dbEvent.FunctionCall.CallInfo = new ReducerCallInfo(ReducerType.StopPlayer, dbEvent.Message, dbEvent.Status, argsGeneric);
		}
	}

	public struct StopPlayerArgsStruct
	{
		public SpacetimeDB.StdbVector2 Location;
	}

	public partial struct ReducerArgs
	{
		[System.Runtime.InteropServices.FieldOffset(0)]
		public StopPlayerArgsStruct StopPlayerArgs;
	}

	public partial class ReducerCallInfo
	{
		public StopPlayerArgsStruct StopPlayerArgs
		{
			get
			{
				if (Reducer != ReducerType.StopPlayer) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "StopPlayer");
				return Args.StopPlayerArgs;
			}
		}
	}
}
