// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void ExtractHandler(ReducerEvent reducerEvent, ulong entityId, ulong resourceEntityId);
		public static event ExtractHandler OnExtractEvent;

		public static void Extract(ulong entityId, ulong resourceEntityId)
		{
			var _argArray = new object[] {entityId, resourceEntityId};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "extract",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "extract")]
		public static bool OnExtract(ClientApi.Event dbEvent)
		{
			if(OnExtractEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).ExtractArgs;
				OnExtractEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(ulong)args.EntityId
					,(ulong)args.ResourceEntityId
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "extract")]
		public static void ExtractDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new ExtractArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.EntityId = args_0_value.AsU64();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.ResourceEntityId = args_1_value.AsU64();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.Extract, "extract", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class ExtractArgsStruct
	{
		public ulong EntityId;
		public ulong ResourceEntityId;
	}

}
