// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public enum ResourceNodeType
	{
		Iron,
	}
}
