// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public delegate void MovePlayerHandler(ReducerEvent reducerEvent, SpacetimeDB.StdbVector2 start, SpacetimeDB.StdbVector2 direction);
		public static event MovePlayerHandler OnMovePlayerEvent;

		public static void MovePlayer(SpacetimeDB.StdbVector2 start, SpacetimeDB.StdbVector2 direction)
		{
			var _argArray = new object[] {start, direction};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "move_player",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "move_player")]
		public static bool OnMovePlayer(ClientApi.Event dbEvent)
		{
			if(OnMovePlayerEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).MovePlayerArgs;
				OnMovePlayerEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.StdbVector2)args.Start
					,(SpacetimeDB.StdbVector2)args.Direction
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "move_player")]
		public static void MovePlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new MovePlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector2.GetAlgebraicType(), reader);
			args.Start = (SpacetimeDB.StdbVector2)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector2.GetAlgebraicType(), reader);
			args.Direction = (SpacetimeDB.StdbVector2)(args_1_value);
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.MovePlayer, "move_player", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class MovePlayerArgsStruct
	{
		public SpacetimeDB.StdbVector2 Start;
		public SpacetimeDB.StdbVector2 Direction;
	}

}
