// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public delegate void StopPlayerHandler(ReducerEvent reducerEvent, SpacetimeDB.StdbVector2 location);
		public static event StopPlayerHandler OnStopPlayerEvent;

		public static void StopPlayer(SpacetimeDB.StdbVector2 location)
		{
			var _argArray = new object[] {location};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "stop_player",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "stop_player")]
		public static bool OnStopPlayer(ClientApi.Event dbEvent)
		{
			if(OnStopPlayerEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).StopPlayerArgs;
				OnStopPlayerEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.StdbVector2)args.Location
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "stop_player")]
		public static void StopPlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new StopPlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector2.GetAlgebraicType(), reader);
			args.Location = (SpacetimeDB.StdbVector2)(args_0_value);
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.StopPlayer, "stop_player", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class StopPlayerArgsStruct
	{
		public SpacetimeDB.StdbVector2 Location;
	}

}
