// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class ActiveTradeComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;
		[Newtonsoft.Json.JsonProperty("trade_session_entity_id")]
		public ulong TradeSessionEntityId;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("trade_session_entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
			});
		}

		public static explicit operator ActiveTradeComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new ActiveTradeComponent
			{
				EntityId = productValue.elements[0].AsU64(),
				TradeSessionEntityId = productValue.elements[1].AsU64(),
			};
		}

		public static System.Collections.Generic.IEnumerable<ActiveTradeComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ActiveTradeComponent"))
			{
				yield return (ActiveTradeComponent)entry;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("ActiveTradeComponent");
		}
		public static ActiveTradeComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ActiveTradeComponent"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (ActiveTradeComponent)entry;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<ActiveTradeComponent> FilterByTradeSessionEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ActiveTradeComponent"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (ulong)productValue.elements[1].AsU64();
				if (compareValue == value) {
					yield return (ActiveTradeComponent)entry;
				}
			}
		}

		public static event Action<ActiveTradeComponent> OnInsert;
		public static event Action<ActiveTradeComponent, ActiveTradeComponent> OnUpdate;
		public static event Action<ActiveTradeComponent> OnDelete;
		public static event Action<NetworkManager.TableOp, ActiveTradeComponent, ActiveTradeComponent> OnRowUpdate;

		public static void OnInsertEvent(object newValue)
		{
			OnInsert?.Invoke((ActiveTradeComponent)newValue);
		}

		public static void OnUpdateEvent(object oldValue, object newValue)
		{
			OnUpdate?.Invoke((ActiveTradeComponent)oldValue,(ActiveTradeComponent)newValue);
		}

		public static void OnDeleteEvent(object oldValue)
		{
			OnDelete?.Invoke((ActiveTradeComponent)oldValue);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue)
		{
			OnRowUpdate?.Invoke(op, (ActiveTradeComponent)oldValue,(ActiveTradeComponent)newValue);
		}
	}
}
