// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class AnimationComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;
		[Newtonsoft.Json.JsonProperty("moving")]
		public bool Moving;
		[Newtonsoft.Json.JsonProperty("action_target_entity_id")]
		public ulong ActionTargetEntityId;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("moving", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.Bool)),
				new SpacetimeDB.SATS.ProductTypeElement("action_target_entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
			});
		}

		public static explicit operator AnimationComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new AnimationComponent
			{
				EntityId = productValue.elements[0].AsU64(),
				Moving = productValue.elements[1].AsBool(),
				ActionTargetEntityId = productValue.elements[2].AsU64(),
			};
		}

		public static System.Collections.Generic.IEnumerable<AnimationComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("AnimationComponent"))
			{
				yield return (AnimationComponent)entry.Item2;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("AnimationComponent");
		}
		public static AnimationComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("AnimationComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (AnimationComponent)entry.Item2;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<AnimationComponent> FilterByMoving(bool value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("AnimationComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (bool)productValue.elements[1].AsBool();
				if (compareValue == value) {
					yield return (AnimationComponent)entry.Item2;
				}
			}
		}

		public static System.Collections.Generic.IEnumerable<AnimationComponent> FilterByActionTargetEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("AnimationComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[2].AsU64();
				if (compareValue == value) {
					yield return (AnimationComponent)entry.Item2;
				}
			}
		}

		public static event Action<AnimationComponent> OnInsert;
		public static event Action<AnimationComponent, AnimationComponent> OnUpdate;
		public static event Action<AnimationComponent> OnDelete;
		public static event Action<NetworkManager.TableOp, AnimationComponent, AnimationComponent> OnRowUpdate;

		public static void OnInsertEvent(object newValue)
		{
			OnInsert?.Invoke((AnimationComponent)newValue);
		}

		public static void OnUpdateEvent(object oldValue, object newValue)
		{
			OnUpdate?.Invoke((AnimationComponent)oldValue,(AnimationComponent)newValue);
		}

		public static void OnDeleteEvent(object oldValue)
		{
			OnDelete?.Invoke((AnimationComponent)oldValue);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue)
		{
			OnRowUpdate?.Invoke(op, (AnimationComponent)oldValue,(AnimationComponent)newValue);
		}
	}
}
