// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class Chunk : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("chunk_id")]
		public ulong ChunkId;
		[Newtonsoft.Json.JsonProperty("position")]
		public SpacetimeDB.ChunkPosition Position;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("chunk_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("position", SpacetimeDB.ChunkPosition.GetAlgebraicType()),
			});
		}

		public static explicit operator Chunk(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new Chunk
			{
				ChunkId = productValue.elements[0].AsU64(),
				Position = (SpacetimeDB.ChunkPosition)(productValue.elements[1]),
			};
		}

		public static System.Collections.Generic.IEnumerable<Chunk> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("Chunk"))
			{
				yield return (Chunk)entry;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("Chunk");
		}
		public static Chunk FilterByChunkId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("Chunk"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (Chunk)entry;
				}
			}
			return null;
		}

		public static event Action<Chunk> OnInsert;
		public static event Action<Chunk, Chunk> OnUpdate;
		public static event Action<Chunk> OnDelete;
		public static event Action<NetworkManager.TableOp, Chunk, Chunk> OnRowUpdate;

		public static void OnInsertEvent(object newValue)
		{
			OnInsert?.Invoke((Chunk)newValue);
		}

		public static void OnUpdateEvent(object oldValue, object newValue)
		{
			OnUpdate?.Invoke((Chunk)oldValue,(Chunk)newValue);
		}

		public static void OnDeleteEvent(object oldValue)
		{
			OnDelete?.Invoke((Chunk)oldValue);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue)
		{
			OnRowUpdate?.Invoke(op, (Chunk)oldValue,(Chunk)newValue);
		}
	}
}
