// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB 
{
	public static partial class Reducer 
	{
		public static void CreateNewPlayer(Position position, Rotation rotation)
		{
			StdbNetworkManager.instance.InternalCallReducer(new StdbNetworkManager.Message
			{
				fn = "create_new_player",
				args = new object[] { position, rotation },
			});
		}
	}
}
