// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace SpacetimeDB
{
	public static partial class Reducer
	{
		public static event Action<ClientApi.Event.Types.Status, Identity, byte[], ulong, ulong, SpacetimeDB.StdbVector3, SpacetimeDB.StdbQuaternion, ulong> OnMoveNpcEvent;

		public static void MoveNpc(byte[] identity, ulong timestamp, ulong entityId, SpacetimeDB.StdbVector3 pos, SpacetimeDB.StdbQuaternion rot, ulong duration)
		{
			var _argArray = new object[] {identity, timestamp, entityId, pos, rot, duration};
			var _message = new NetworkManager.ReducerCallRequest {
				fn = "move_npc",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			NetworkManager.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerEvent(FunctionName = "move_npc")]
		public static void OnMoveNpc(ClientApi.Event dbEvent)
		{
			if(OnMoveNpcEvent != null)
			{
				var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
				using var ms = new System.IO.MemoryStream();
				ms.SetLength(bsatnBytes.Length);
				bsatnBytes.CopyTo(ms.GetBuffer(), 0);
				ms.Position = 0;
				using var reader = new System.IO.BinaryReader(ms);
				var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreateArrayType(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U8)), reader);
				var args_0 = args_0_value.AsBytes();
				var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
				var args_1 = args_1_value.AsU64();
				var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
				var args_2 = args_2_value.AsU64();
				var args_3_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector3.GetAlgebraicType(), reader);
				var args_3 = (SpacetimeDB.StdbVector3)(args_3_value);
				var args_4_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbQuaternion.GetAlgebraicType(), reader);
				var args_4 = (SpacetimeDB.StdbQuaternion)(args_4_value);
				var args_5_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
				var args_5 = args_5_value.AsU64();
				OnMoveNpcEvent(dbEvent.Status, Identity.From(dbEvent.CallerIdentity.ToByteArray()), args_0, args_1, args_2, args_3, args_4, args_5);
			}
		}
		[DeserializeEvent(FunctionName = "move_npc")]
		public static object[] MoveNpcDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreateArrayType(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U8)), reader);
			var args_0 = args_0_value.AsBytes();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			var args_1 = args_1_value.AsU64();
			var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			var args_2 = args_2_value.AsU64();
			var args_3_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbVector3.GetAlgebraicType(), reader);
			var args_3 = (SpacetimeDB.StdbVector3)(args_3_value);
			var args_4_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.StdbQuaternion.GetAlgebraicType(), reader);
			var args_4 = (SpacetimeDB.StdbQuaternion)(args_4_value);
			var args_5_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			var args_5 = args_5_value.AsU64();
			return new object[] {
				args_0,
				args_1,
				args_2,
				args_3,
				args_4,
				args_5,
			};
		}
	}
}
