// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB 
{
	public static partial class Reducer 
	{
		public static void MovePlayer(u32 playerId, f32 x, f32 y, f32 z)
		{
			StdbNetworkManager.SendMessage(new Message
			{
				fn = "Func",
				args = new object[] { playerId, x, y, z }
			});
		}
	}
}
