// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB 
{
	public static partial class Reducer 
	{
		public static void MovePlayer(byte[] sender, ulong timestamp, uint playerId, float x, float y, float z)
		{
			StdbNetworkManager.instance.InternalCallReducer(new StdbNetworkManager.Message
			{
				fn = "move_player",
				args = new object[] { sender, timestamp, playerId, x, y, z },
			});
		}
	}
}
