// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class PlayerLoginComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;
		[Newtonsoft.Json.JsonProperty("logged_in")]
		public bool LoggedIn;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("logged_in", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.Bool)),
			});
		}

		public static explicit operator PlayerLoginComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new PlayerLoginComponent
			{
				EntityId = productValue.elements[0].AsU64(),
				LoggedIn = productValue.elements[1].AsBool(),
			};
		}

		public static System.Collections.Generic.IEnumerable<PlayerLoginComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerLoginComponent"))
			{
				yield return (PlayerLoginComponent)entry.Item2;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("PlayerLoginComponent");
		}
		public static PlayerLoginComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerLoginComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (PlayerLoginComponent)entry.Item2;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<PlayerLoginComponent> FilterByLoggedIn(bool value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerLoginComponent"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (bool)productValue.elements[1].AsBool();
				if (compareValue == value) {
					yield return (PlayerLoginComponent)entry.Item2;
				}
			}
		}

		public static event Action<PlayerLoginComponent> OnInsert;
		public static event Action<PlayerLoginComponent, PlayerLoginComponent> OnUpdate;
		public static event Action<PlayerLoginComponent> OnDelete;
		public static event Action<NetworkManager.TableOp, PlayerLoginComponent, PlayerLoginComponent> OnRowUpdate;

		public static void OnInsertEvent(object newValue)
		{
			OnInsert?.Invoke((PlayerLoginComponent)newValue);
		}

		public static void OnUpdateEvent(object oldValue, object newValue)
		{
			OnUpdate?.Invoke((PlayerLoginComponent)oldValue,(PlayerLoginComponent)newValue);
		}

		public static void OnDeleteEvent(object oldValue)
		{
			OnDelete?.Invoke((PlayerLoginComponent)oldValue);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue)
		{
			OnRowUpdate?.Invoke(op, (PlayerLoginComponent)oldValue,(PlayerLoginComponent)newValue);
		}
	}
}
