// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class PlayerComponent : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("entity_id")]
		public ulong EntityId;
		[Newtonsoft.Json.JsonProperty("owner_id")]
		[Newtonsoft.Json.JsonConverter(typeof(SpacetimeDB.ByteArrayConverter))]
		public byte[] OwnerId;
		[Newtonsoft.Json.JsonProperty("username")]
		public string Username;
		[Newtonsoft.Json.JsonProperty("creation_time")]
		public ulong CreationTime;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("entity_id", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
				new SpacetimeDB.SATS.ProductTypeElement("owner_id", SpacetimeDB.SATS.AlgebraicType.CreateArrayType(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U8))),
				new SpacetimeDB.SATS.ProductTypeElement("username", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String)),
				new SpacetimeDB.SATS.ProductTypeElement("creation_time", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
			});
		}

		public static explicit operator PlayerComponent(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new PlayerComponent
			{
				EntityId = productValue.elements[0].AsU64(),
				OwnerId = productValue.elements[1].AsBytes(),
				Username = productValue.elements[2].AsString(),
				CreationTime = productValue.elements[3].AsU64(),
			};
		}

		public static System.Collections.Generic.IEnumerable<PlayerComponent> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerComponent"))
			{
				yield return (PlayerComponent)entry;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("PlayerComponent");
		}
		public static PlayerComponent FilterByEntityId(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerComponent"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (ulong)productValue.elements[0].AsU64();
				if (compareValue == value) {
					return (PlayerComponent)entry;
				}
			}
			return null;
		}

		public static PlayerComponent FilterByOwnerId(byte[] value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerComponent"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (byte[])productValue.elements[1].AsBytes();
				static bool ByteArrayCompare(byte[] a1, byte[] a2)
				{
				    if (a1.Length != a2.Length)
				        return false;

				    for (int i=0; i<a1.Length; i++)
				        if (a1[i]!=a2[i])
				            return false;

				    return true;
				}

				if (ByteArrayCompare(compareValue, value)) {
					return (PlayerComponent)entry;
				}
			}
			return null;
		}

		public static PlayerComponent FilterByUsername(string value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerComponent"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (string)productValue.elements[2].AsString();
				if (compareValue == value) {
					return (PlayerComponent)entry;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<PlayerComponent> FilterByCreationTime(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("PlayerComponent"))
			{
				var productValue = entry.AsProductValue();
				var compareValue = (ulong)productValue.elements[3].AsU64();
				if (compareValue == value) {
					yield return (PlayerComponent)entry;
				}
			}
		}

		public static event Action<PlayerComponent> OnInsert;
		public static event Action<PlayerComponent, PlayerComponent> OnUpdate;
		public static event Action<PlayerComponent> OnDelete;
		public static event Action<NetworkManager.TableOp, PlayerComponent, PlayerComponent> OnRowUpdate;

		public static void OnInsertEvent(object newValue)
		{
			OnInsert?.Invoke((PlayerComponent)newValue);
		}

		public static void OnUpdateEvent(object oldValue, object newValue)
		{
			OnUpdate?.Invoke((PlayerComponent)oldValue,(PlayerComponent)newValue);
		}

		public static void OnDeleteEvent(object oldValue)
		{
			OnDelete?.Invoke((PlayerComponent)oldValue);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue)
		{
			OnRowUpdate?.Invoke(op, (PlayerComponent)oldValue,(PlayerComponent)newValue);
		}
	}
}
