// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB
{
	public partial class Position
	{
		[Newtonsoft.Json.JsonProperty("pos_x")]		public float posX;
		[Newtonsoft.Json.JsonProperty("pos_y")]		public float posY;
		[Newtonsoft.Json.JsonProperty("pos_z")]		public float posZ;
	}
}
