// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;

namespace SpacetimeDB
{
	public partial class ServerGlobals : IDatabaseTable
	{
		[Newtonsoft.Json.JsonProperty("version")]
		public uint Version;
		[Newtonsoft.Json.JsonProperty("entity_id_counter")]
		public ulong EntityIdCounter;

		public static SpacetimeDB.SATS.AlgebraicType GetAlgebraicType()
		{
			return SpacetimeDB.SATS.AlgebraicType.CreateProductType(new SpacetimeDB.SATS.ProductTypeElement[]
			{
				new SpacetimeDB.SATS.ProductTypeElement("version", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U32)),
				new SpacetimeDB.SATS.ProductTypeElement("entity_id_counter", SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)),
			});
		}

		public static explicit operator ServerGlobals(SpacetimeDB.SATS.AlgebraicValue value)
		{
			if (value == null) {
				return null;
			}
			var productValue = value.AsProductValue();
			return new ServerGlobals
			{
				Version = productValue.elements[0].AsU32(),
				EntityIdCounter = productValue.elements[1].AsU64(),
			};
		}

		public static System.Collections.Generic.IEnumerable<ServerGlobals> Iter()
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ServerGlobals"))
			{
				yield return (ServerGlobals)entry.Item2;
			}
		}
		public static int Count()
		{
			return NetworkManager.clientDB.Count("ServerGlobals");
		}
		public static ServerGlobals FilterByVersion(uint value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ServerGlobals"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (uint)productValue.elements[0].AsU32();
				if (compareValue == value) {
					return (ServerGlobals)entry.Item2;
				}
			}
			return null;
		}

		public static System.Collections.Generic.IEnumerable<ServerGlobals> FilterByEntityIdCounter(ulong value)
		{
			foreach(var entry in NetworkManager.clientDB.GetEntries("ServerGlobals"))
			{
				var productValue = entry.Item1.AsProductValue();
				var compareValue = (ulong)productValue.elements[1].AsU64();
				if (compareValue == value) {
					yield return (ServerGlobals)entry.Item2;
				}
			}
		}

		public static event Action<ServerGlobals> OnInsert;
		public static event Action<ServerGlobals, ServerGlobals> OnUpdate;
		public static event Action<ServerGlobals> OnDelete;
		public static event Action<NetworkManager.TableOp, ServerGlobals, ServerGlobals> OnRowUpdate;

		public static void OnInsertEvent(object newValue)
		{
			OnInsert?.Invoke((ServerGlobals)newValue);
		}

		public static void OnUpdateEvent(object oldValue, object newValue)
		{
			OnUpdate?.Invoke((ServerGlobals)oldValue,(ServerGlobals)newValue);
		}

		public static void OnDeleteEvent(object oldValue)
		{
			OnDelete?.Invoke((ServerGlobals)oldValue);
		}

		public static void OnRowUpdateEvent(NetworkManager.TableOp op, object oldValue, object newValue)
		{
			OnRowUpdate?.Invoke(op, (ServerGlobals)oldValue,(ServerGlobals)newValue);
		}
	}
}
