// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using SpacetimeDB;namespace SpacetimeDB
 {
	public partial class Inventory
 {
		public uint pocketCount;
		public Pocket pocket;
	}
