// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB 
{
	public static partial class Reducer 
	{
		public static void MovePlayer(uint playerId, Position position, Rotation rotation, bool moving)
		{
			StdbNetworkManager.instance.InternalCallReducer(new StdbNetworkManager.Message
			{
				fn = "move_player",
				args = new object[] { playerId, position, rotation, moving },
			});
		}
	}
}
