// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB
{
	public partial class Player
	{
		[Newtonsoft.Json.JsonProperty("player_id")]
		public uint playerId;
		[Newtonsoft.Json.JsonProperty("position")]
		public Position position;
	}
}
