// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB
{
	public partial class Player
	{
		[Newtonsoft.Json.JsonProperty("player_id")]
		public uint playerId;
		[Newtonsoft.Json.JsonProperty("position")]
		public Position position;
		[Newtonsoft.Json.JsonProperty("rotation")]
		public Rotation rotation;
		[Newtonsoft.Json.JsonProperty("moving")]
		public bool moving;
		public static TypeDef GetTypeDef()
		{
			return TypeDef.Tuple(new ElementDef[]
			{
				new SpacetimeDB.ElementDef(0, SpacetimeDB.TypeDef.BuiltInType(SpacetimeDB.TypeDef.Def.U32)),
				new SpacetimeDB.ElementDef(1, SpacetimeDB.Position.GetTypeDef()),
				new SpacetimeDB.ElementDef(2, SpacetimeDB.Rotation.GetTypeDef()),
				new SpacetimeDB.ElementDef(3, SpacetimeDB.TypeDef.BuiltInType(SpacetimeDB.TypeDef.Def.Bool)),
			});
		}
	}
}
